version: "3"

services:
  glue:
    container_name: glue
    build:
      dockerfile: "./Dockerfile"
      context: "./"
    command: "tail -f /dev/null"
    working_dir: "/project"
    volumes:
      - "./:/project"
    environment:
      TF_VAR_glue_bucket_name: ${TF_VAR_glue_bucket_name}
      TF_STATE_BUCKET: ${TF_STATE_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      TERRAFORM_VERSION: 0.14.3
